### ISSUE TITLE
failed to wget  driverChanges.txt.gz when  build sql-client

### ISSUE THREAD

**Issue by SwimSweet** [ververica/sql-training#18]
--2021-02-01 13:11:16--  https://drive.google.com/uc?export=download&id=1pf4tfv-YpoVQ9_O0948M8oXeCfVH-0MH
Resolving drive.google.com (drive.google.com)... 203.208.46.146, 74.125.71.94
Connecting to drive.google.com (drive.google.com)|203.208.46.146|:443... failed: Connection refused.
Connecting to drive.google.com (drive.google.com)|74.125.71.94|:443... failed: Connection refused.
--2021-02-01 13:11:58--  https://drive.google.com/uc?export=download&id=1SriiwcIdMvY7uJsWSY4Hhh32iO3F4ND2
Resolving drive.google.com (drive.google.com)... 203.208.46.146, 74.125.71.94
Connecting to drive.google.com (drive.google.com)|203.208.46.146|:443... failed: Connection refused.
Connecting to drive.google.com (drive.google.com)|74.125.71.94|:443... failed: Connection refused.
--2021-02-01 13:12:42--  https://drive.google.com/uc?export=download&id=1gY8W07OFvB7_4lHlAyingM4WQzs0_8lT
Resolving drive.google.com (drive.google.com)... 203.208.46.146, 74.125.71.94
Connecting to drive.google.com (drive.google.com)|203.208.46.146|:443... failed: Connection refused.
Connecting to drive.google.com (drive.google.com)|74.125.71.94|:443... failed: Connection refused.
ERROR: Service 'sql-client' failed to build : The command '/bin/sh -c wget -P /opt/sql-client/lib/ https://repo.maven.apache.org/maven2/org/apache/flink/flink-json/${FLINK_VERSION}/flink-json-${FLINK_VERSION}.jar;     wget -P /opt/sql-client/lib/ https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka_2.11/${FLINK_VERSION}/flink-sql-connector-kafka_2.11-${FLINK_VERSION}.jar;     wget -P /opt/sql-client/lib/ https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-filesystem_2.11/${FLINK_VERSION}/flink-connector-filesystem_2.11-${FLINK_VERSION}.jar;     wget -P /opt/flink/lib https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.7.5-8.0/flink-shaded-hadoop-2-uber-2.7.5-8.0.jar;     wget -P /opt/sql-client/lib/ https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jdbc_2.11/${FLINK_VERSION}/flink-connector-jdbc_2.11-${FLINK_VERSION}.jar;     wget -P /opt/sql-client/lib/ https://repo.maven.apache.org/maven2/mysql/mysql-connector-java/8.0.19/mysql-connector-java-8.0.19.jar;     mkdir -p /opt/data;     mkdir -p /opt/data/stream;     wget -O /opt/data/driverChanges.txt.gz 'https://drive.google.com/uc?export=download&id=1pf4tfv-YpoVQ9_O0948M8oXeCfVH-0MH';     wget -O /opt/data/fares.txt.gz 'https://drive.google.com/uc?export=download&id=1SriiwcIdMvY7uJsWSY4Hhh32iO3F4ND2';     wget -O /opt/data/rides.txt.gz 'https://drive.google.com/uc?export=download&id=1gY8W07OFvB7_4lHlAyingM4WQzs0_8lT';' returned a non-zero code: 4

**Comment by ChenShuai1981** [comment]
I got the same issue :-(
