### ISSUE TITLE
how to use my own config.yaml

### ISSUE THREAD

**Issue by sunfu103** [ververica/sql-training#2]
(base) localhost:~ sunfu$ docker-compose exec sql-client ./sql-client.sh
Reading default environment from: file:/opt/sql-client/conf/config.yaml
No session environment specified.
Validating current environment...done.

[Reading default environment from: file:/opt/sql-client/conf/config.yaml] how to overwrite de config.yaml

**Comment by fhueske** [comment]
I didn't design the sql-client image to be able to load custom configs. The easiest would probably be to build a custom sql-client image. The require code is in the `./build-image` folder.
Thanks, Fabian
