### ISSUE TITLE
training-config.yaml 404 not found

### ISSUE THREAD

**Issue by aquarius-wing** [ververica/sql-training#3]
在博客中[Flink SQL 编程实践](http://wuchong.me/blog/2019/08/20/flink-sql-training/#more)中提到了链接[training-config.yaml](https://github.com/ververica/sql-training/blob/master/build-image/training-config.yaml)，在[最新一次提交](https://github.com/ververica/sql-training/commit/90cb56ec3a0a3ccd74e32e0269917f614d5450d5)过程中把这个文件删除了，是误操作了吗？

**Comment by fhueske** [comment]
The training config was moved to `https://github.com/ververica/sql-training/blob/master/build-image/conf/flink-conf.yaml`.
Sorry for the inconvenience, Fabian
