### ISSUE TITLE
Elasticsearch URLs on wiki/Introduction-to-SQL-on-Flink are inconsistent

### ISSUE THREAD

**Issue by mchro** [ververica/sql-training#4]
On https://github.com/ververica/sql-training/wiki/Introduction-to-SQL-on-Flink the URLs are refering to "area-cnt":
![image](https://user-images.githubusercontent.com/2332229/66562557-33cb7080-eb5c-11e9-951a-473d1178b6ef.png)
while on https://github.com/ververica/sql-training/wiki/Ecosystem-and-Writing-to-External-Tables the URLs are refering to "area-cnts" (which is the correct one, that is actually generated).

**Comment by fhueske** [comment]
Thanks for reporting this error @mchro and sorry for the super slow response on this one.
It's fixed now.

Thank you, Fabian
