### ISSUE TITLE
Cannot create container for service jobmanager: b'Invalid container name (_jobmanager_1), only [a-zA-Z0Creating _zookeeper_1  

### ISSUE THREAD

**Issue by sherry255** [ververica/sql-training#7]
Status: Downloaded newer image for fhueske/flink-sql-client-training-1.7.2:latest
Creating _elasticsearch_1 ... error
Creating _jobmanager_1    ...
Creating _zookeeper_1     ...

Creating _jobmanager_1    ... error
 [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed'

ERROR: for _jobmanager_1  Cannot create container for service jobmanager: b'Invalid container name (_jobmanager_1), only [a-zA-Z0Creating _zookeeper_1     ... error

ERROR: for _zookeeper_1  Cannot create container for service zookeeper: b'Invalid container name (_zookeeper_1), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed'

ERROR: for elasticsearch  Cannot create container for service elasticsearch: b'Invalid container name (_elasticsearch_1), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed'

ERROR: for jobmanager  Cannot create container for service jobmanager: b'Invalid container name (_jobmanager_1), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed'

ERROR: for zookeeper  Cannot create container for service zookeeper: b'Invalid container name (_zookeeper_1), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed'
ERROR: Encountered errors while bringing up the project.

**Comment by fhueske** [comment]
`flink-sql-client-training-1.7.2:latest` looks like an old version.

Did you try to pull the latest version of the repository?
Which commands did you run?
